import sqlite3
import os
import hashlib
import binascii
import uuid
import hmac
import base64
from flask import current_app

def hash_pgadmin_password(password, salt):
    """
    Generate a hash compatible with flask-security-too (used by pgAdmin 4).
    Flask-Security-Too HMACs the password using the security salt before hashing.
    """
    from passlib.hash import pbkdf2_sha512
    # 1. HMAC the password using the salt as the key
    pw_hmac = hmac.new(salt.encode('utf-8'), password.encode('utf-8'), hashlib.sha512).digest()
    # 2. Base64 encode the resulting digest
    pw_b64 = base64.b64encode(pw_hmac).decode('utf-8')
    # 3. Hash the resulting string using PBKDF2-SHA512
    return pbkdf2_sha512.hash(pw_b64)

def sync_user_to_pgadmin(db_username, db_password):
    """
    Create or update a pgAdmin 4 user account for a database user.
    Also adds the localhost server entry.
    """
    db_path = current_app.config.get('PGADMIN_DB_PATH', '/var/lib/pgadmin/pgadmin4.db')
    salt = current_app.config.get('PGADMIN_SECURITY_PASSWORD_SALT', 'default-salt')
    
    if not os.path.exists(db_path):
        current_app.logger.warning(f"pgAdmin database not found at {db_path}. Skipping sync.")
        return False

    email = f"{db_username}@localhost"
    hashed_password = hash_pgadmin_password(db_password, salt)

    try:
        conn = sqlite3.connect(db_path)
        cursor = conn.cursor()

        # 1. Ensure user exists
        cursor.execute("SELECT id FROM user WHERE username = ?", (email,))
        user = cursor.fetchone()
        
        if not user:
            uniquifier = uuid.uuid4().hex
            cursor.execute(
                "INSERT INTO user (username, password, active, confirmed_at, fs_uniquifier) VALUES (?, ?, ?, datetime('now'), ?)",
                (email, hashed_password, 1, uniquifier)
            )
            user_id = cursor.lastrowid
        else:
            user_id = user[0]
            cursor.execute("UPDATE user SET password = ? WHERE id = ?", (hashed_password, user_id))

        # 3. Add localhost server for this user
        # Check if server already exists for this user
        cursor.execute("SELECT id FROM server WHERE user_id = ? AND name = ?", (user_id, 'Localhost'))
        server = cursor.fetchone()

        if not server:
            # We insert with the specific schema found on the host:
            # ['id', 'user_id', 'servergroup_id', 'name', 'host', 'port', 'maintenance_db', 'username', 'comment', ...]
            # Note: servergroup_id 1 is the default "Servers" group.
            cursor.execute(
                """INSERT INTO server (user_id, servergroup_id, name, host, port, maintenance_db, username, comment) 
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
                (user_id, 1, 'Localhost', 'localhost', 5432, 'postgres', db_username, 'Auto-generated by VPS Panel')
            )

        conn.commit()
        conn.close()
        current_app.logger.info(f"Successfully synced {db_username} to pgAdmin.")
        return True
    except Exception as e:
        current_app.logger.error(f"Failed to sync user to pgAdmin: {e}")
        return False
