import sqlite3
import os
import hashlib
import binascii
import uuid
from flask import current_app

def hash_pgadmin_password(password, salt):
    """
    Generate a pbkdf2_sha512 hash compatible with flask-security-too (used by pgAdmin 4).
    Note: Real implementation may vary slightly based on pgAdmin version.
    """
    # This is a simplified version. pgAdmin uses passlib's pbkdf2_sha512.
    # In production, we'd ideally use passlib directly.
    from passlib.hash import pbkdf2_sha512
    return pbkdf2_sha512.using(salt=salt.encode()).hash(password)

def sync_user_to_pgadmin(db_username, db_password):
    """
    Create or update a pgAdmin 4 user account for a database user.
    Also adds the localhost server entry.
    """
    db_path = current_app.config.get('PGADMIN_DB_PATH', '/var/lib/pgadmin/pgadmin4.db')
    salt = current_app.config.get('PGADMIN_SECURITY_PASSWORD_SALT', 'default-salt')
    
    if not os.path.exists(db_path):
        current_app.logger.warning(f"pgAdmin database not found at {db_path}. Skipping sync.")
        return False

    email = f"{db_username}@localhost"
    hashed_password = hash_pgadmin_password(db_password, salt)

    try:
        conn = sqlite3.connect(db_path)
        cursor = conn.cursor()

        # 1. Ensure user exists
        cursor.execute("SELECT id FROM user WHERE username = ?", (email,))
        user = cursor.fetchone()
        
        if not user:
            uniquifier = uuid.uuid4().hex
            cursor.execute(
                "INSERT INTO user (username, password, active, confirmed_at, fs_uniquifier) VALUES (?, ?, ?, datetime('now'), ?)",
                (email, hashed_password, 1, uniquifier)
            )
            user_id = cursor.lastrowid
        else:
            user_id = user[0]
            cursor.execute("UPDATE user SET password = ? WHERE id = ?", (hashed_password, user_id))

        # 2. Add localhost server for this user
        # Check if server already exists for this user
        cursor.execute("SELECT id FROM server WHERE user_id = ? AND name = ?", (user_id, 'Localhost'))
        server = cursor.fetchone()

        if not server:
            # We insert with basic settings. pgAdmin 4 schema has many columns.
            # Usually: user_id, name, host, port, maintenance_db, username, ssl_mode
            cursor.execute(
                """INSERT INTO server (user_id, name, host, port, maintenance_db, username, ssl_mode, comment) 
                   VALUES (?, ?, ?, ?, ?, ?, ?, ?)""",
                (user_id, 'Localhost', 'localhost', 5432, 'postgres', db_username, 'prefer', 'Auto-generated by VPS Panel')
            )

        conn.commit()
        conn.close()
        current_app.logger.info(f"Successfully synced {db_username} to pgAdmin.")
        return True
    except Exception as e:
        current_app.logger.error(f"Failed to sync user to pgAdmin: {e}")
        return False
